ignore-interior-mutability = ["bytes::Bytes", "queue_runner::build::Step"]
disallowed-methods = [
  { path = "std::fs::canonicalize", replacement = "fs_err::canonicalize" },
  { path = "std::fs::copy", replacement = "fs_err::copy" },
  { path = "std::fs::create_dir", replacement = "fs_err::create_dir" },
  { path = "std::fs::create_dir_all", replacement = "fs_err::create_dir_all" },
  { path = "std::fs::exists", replacement = "fs_err::exists" },
  { path = "std::fs::hard_link", replacement = "fs_err::hard_link" },
  { path = "std::fs::metadata", replacement = "fs_err::metadata" },
  { path = "std::fs::read", replacement = "fs_err::read" },
  { path = "std::fs::read_dir", replacement = "fs_err::read_dir" },
  { path = "std::fs::read_link", replacement = "fs_err::read_link" },
  { path = "std::fs::read_to_string", replacement = "fs_err::read_to_string" },
  { path = "std::fs::remove_dir", replacement = "fs_err::remove_dir" },
  { path = "std::fs::remove_dir_all", replacement = "fs_err::remove_dir_all" },
  { path = "std::fs::remove_file", replacement = "fs_err::remove_file" },
  { path = "std::fs::rename", replacement = "fs_err::rename" },
  { path = "std::fs::set_permissions", replacement = "fs_err::set_permissions" },
  { path = "std::fs::symlink_metadata", replacement = "fs_err::symlink_metadata" },
  { path = "std::fs::write", replacement = "fs_err::write" },
  { path = "std::fs::File::open", replacement = "fs_err::File::open" },
  { path = "std::fs::File::create", replacement = "fs_err::File::create" },
  { path = "std::fs::File::create_new", replacement = "fs_err::File::create_new" },
  { path = "std::fs::OpenOptions::new", replacement = "fs_err::OpenOptions::new" },

  { path = "std::os::unix::fs::symlink", replacement = "fs_err::os::unix::symlink" },

  { path = "std::path::Path::try_exists", reason = "Use fs_err::path::PathExt methods" },
  { path = "std::path::Path::metadata", reason = "Use fs_err::path::PathExt methods" },
  { path = "std::path::Path::symlink_metadata", reason = "Use fs_err::path::PathExt methods" },
  { path = "std::path::Path::canonicalize", reason = "Use fs_err::path::PathExt methods" },
  { path = "std::path::Path::read_link", reason = "Use fs_err::path::PathExt methods" },
  { path = "std::path::Path::read_dir", reason = "Use fs_err::path::PathExt methods" },

  { path = "tokio::fs::canonicalize", replacement = "fs_err::tokio::canonicalize" },
  { path = "tokio::fs::copy", replacement = "fs_err::tokio::copy" },
  { path = "tokio::fs::create_dir", replacement = "fs_err::tokio::create_dir" },
  { path = "tokio::fs::create_dir_all", replacement = "fs_err::tokio::create_dir_all" },
  { path = "tokio::fs::hard_link", replacement = "fs_err::tokio::hard_link" },
  { path = "tokio::fs::metadata", replacement = "fs_err::tokio::metadata" },
  { path = "tokio::fs::read", replacement = "fs_err::tokio::read" },
  { path = "tokio::fs::read_dir", replacement = "fs_err::tokio::read_dir" },
  { path = "tokio::fs::read_link", replacement = "fs_err::tokio::read_link" },
  { path = "tokio::fs::read_to_string", replacement = "fs_err::tokio::read_to_string" },
  { path = "tokio::fs::remove_dir", replacement = "fs_err::tokio::remove_dir" },
  { path = "tokio::fs::remove_dir_all", replacement = "fs_err::tokio::remove_dir_all" },
  { path = "tokio::fs::remove_file", replacement = "fs_err::tokio::remove_file" },
  { path = "tokio::fs::rename", replacement = "fs_err::tokio::rename" },
  { path = "tokio::fs::set_permissions", replacement = "fs_err::tokio::set_permissions" },
  { path = "tokio::fs::symlink_metadata", replacement = "fs_err::tokio::symlink_metadata" },
  { path = "tokio::fs::write", replacement = "fs_err::tokio::write" },
  { path = "tokio::fs::File::open", replacement = "fs_err::tokio::File::open" },
  { path = "tokio::fs::File::create", replacement = "fs_err::tokio::File::create" },
  { path = "tokio::fs::File::create_new", replacement = "fs_err::tokio::File::create_new" },
  { path = "tokio::fs::OpenOptions::new", replacement = "fs_err::tokio::OpenOptions::new" },
]
